### ISSUE TITLE
TypeError: Cannot read property 'getAuthInstance' of undefined HTMLButtonElement.<anonymous>(office.web)

### ISSUE THREAD

**Issue by juliemar** [ResultadosDigitais/matrix#105]
https://sentry.io/share/issue/bbeee478e6424a9fbc70a67c5b8c3062/

<!--- kind: bug , priority: medium

## Description
the sentry.io is reporting TypeErrorHTMLButtonElement.<anonymous>(office.web) 

### Steps to Reproduce
access: https://sentry.io/share/issue/bbeee478e6424a9fbc70a67c5b8c3062/

**Comment by lccezinha** [comment]
The code that is shown in the snippet does not seem to be updated :thinking: https://github.com/ResultadosDigitais/matrix/blob/f0db81f9759f03bd2adc56678f05858eb3121024/public/js/office.web.js#L19

**Comment by juliemar** [comment]
Is not to reproduce this issue
