### ISSUE TITLE
 TypeErrorMatrixProfile.prototype.userName(profile.web) JSON.parse(...) is null

### ISSUE THREAD

**Issue by juliemar** [ResultadosDigitais/matrix#106]
<!--- Do not forget to inform the issue's 
kind: bug , priority: low

## Description
sentry.io is reporting this error: 
TypeErrorMatrixProfile.prototype.userName(profile.web)
JSON.parse(...) is null

### Steps to Reproduce
access: https://sentry.io/share/issue/ee5642b25a8b4070a1f5f1801181f3a9/

**Comment by juliemar** [comment]
more details here: https://sentry.io/share/issue/ee5642b25a8b4070a1f5f1801181f3a9/

**Comment by alesshh** [comment]
it does not occurres anymore
