### ISSUE TITLE
right click to get user in meet doesn't work

### ISSUE THREAD

**Issue by juliemar** [ResultadosDigitais/matrix#131]
## Description
When I want to get a user to my room and this user is in the meeting in another room the right click menu "Get" don't work.    

### Steps to Reproduce
1. Stay logged with 2 users
2. enter in the room with user A and start a Meet
3. With user B in a different room try to execute right click on the User A avatar.

### Expected Behavior
- expected to appear the Get menu
![image](https://user-images.githubusercontent.com/643779/57028040-61f36e80-6c14-11e9-9d60-5fecfeea3873.png)

### Current Behavior
- current behavior appears only the native browser context menu 
![image](https://user-images.githubusercontent.com/643779/57028154-bac30700-6c14-11e9-81fd-7799a1455976.png)

**Comment by alesshh** [comment]
@juliemar fixed?

**Comment by juliemar** [comment]
Yes, I believe the PR with webpack we Fixed this issue...
