### ISSUE TITLE
Firefox visualization issue

### ISSUE THREAD

**Issue by Seralto** [ResultadosDigitais/matrix#135]
Modal not showed properly in Firefox 66.0.3 (64-bit).
The height is small as one can see in the following pic:

![image](https://user-images.githubusercontent.com/6744006/57081087-68442200-6cca-11e9-9d36-2ab61269079f.png)

**Comment by dvinciguerra** [comment]
+1

**Comment by alesshh** [comment]
Closed by https://github.com/ResultadosDigitais/matrix/pull/138
