### ISSUE TITLE
Add Hability to Minimize the Modal Meeting View

### ISSUE THREAD

**Issue by raphaelln** [ResultadosDigitais/matrix#137]
It would be nice if the modal view has capability to be minimized or resized.

When user is in the meeting he cannot see the rooms to see if a user is available to call him to enter in the meeting.

**Comment by matheuslc** [comment]
@raphaelln The ongoing meeting will be disconnected?

I think opening the meeting inside a modal is a UX Debt. Sometimes, during a meeting, it's easy to misclick outside the modal and this closes the modal and meeting unexpectedly.

Just 2cents

**Comment by lccezinha** [comment]
@matheuslc this bug was fixed here #128

**Comment by alesshh** [comment]
I like the idea to get someone to current call but minimize the modal maybe isn't possible.
it would be cool if it had a sidebar with active users during calls.

**Comment by kaiofelipejs** [comment]
I believe that this issue is solved in the new layout ([Morpheus](https://github.com/ResultadosDigitais/matrix/pull/174)), right? 

Make sense this issue stays open?

**Comment by juliemar** [comment]
The new layout Morpheus fixed this issue
