### ISSUE TITLE
Add Hability to define trusted login domains

### ISSUE THREAD

**Issue by juliemar** [ResultadosDigitais/matrix#143]
## Description
I'd like to close my office to enable only users with a trusted e-mail to enter my office.    

### Describe alternatives you've considered
in MVP mode we can use an environment variable with the list of trusted e-mail domains.

**Comment by magnocosta** [comment]
@juliemar, 

Existe alguma motivação para que não tenha um banco de dados onde podemos colocar todas as configurações?

Vejo que essa feature é bem legal, faz sentido no meu ambiente e olhando a maneira como as configurações são realizadas (via env's) não me parece e melhor modelo. Entendo que no MVP isso faz sentido, mas acho que já vale adicionar um bd.

Se achar que faz sentido, veja a minha proposta:

1. Adicionar um banco de dados, pode ser um postgres ou algo mais leve.
2. Adicionar essa banco no docker compose, para que o run já configure tudo (até com valores default)
3. Adicionar um admin (CRUD) para registrar os emails ou um domínio especifico. Nesse primeiro momento nem precisa ter login de acesso ao admin.
4. Adicionar uma restrição no controler de login para verificar se o email que acabou de se autenticar no Google está dentro dessa whitelist.

Se seguirmos assim os próximos passos pode ser migrar todas as configs para essa estrutura.

Veja se faz sentido, se fizer, Eu posso trabalhar nisso.

\o/ \o/ \o/

**Comment by angeliski** [comment]
Hey @juliemar Que acha de seguirmos com isso? Você tem alguma sugestão de banco de dados?

**Comment by magnocosta** [comment]
Bom vou tocar um PR disso @angeliski, se vc tiver interesse vamos nos falamos e tocamos juntos

**Comment by magnocosta** [comment]
Pessoal,

Só para deixar registrado, cai nesse mesmo problema aqui ao instalar a Matrix para o meu time. Inicialmente subimos a aplicação por trás da nossa VPN porém, por vários problemas na nossa VPN, a conexão está ruim e instável.

Decidimos então liberar na internet, sem precisar do uso da VPN, o problema com isso é que qualquer pessoa com Gmail pode logar na Matrix.

Vou trabalhar nessa feature aqui já que vai ajudar muito o meu time a continuar usando a ferramenta. Ainda não vi se o serviço do Google de Autenticação já permite esse filtro, se alguém souber de algo posta ae.

Abs!

**Comment by angeliski** [comment]
Manda bala @magnocosta eu comecei a ver isso, mas acabei enrolado. Um dos problemas que eu vi na época é que o login é todo feito no front, talvez tenha que mudar isso, não sei... Ou então validar o token a cada requisição seja uma alternativa

**Comment by megatroom** [comment]
> @juliemar,
> 
> Existe alguma motivação para que não tenha um banco de dados onde podemos colocar todas as configurações?
> 
> Vejo que essa feature é bem legal, faz sentido no meu ambiente e olhando a maneira como as configurações são realizadas (via env's) não me parece e melhor modelo. Entendo que no MVP isso faz sentido, mas acho que já vale adicionar um bd.

Ótimas sugestões @magnocosta :muscle: :rocket: 

> 
> Se achar que faz sentido, veja a minha proposta:
> 
> 1. Adicionar um banco de dados, pode ser um postgres ou algo mais leve.

Isso poderia ser configurável e agnóstico, assim a empresa poderia usar o banco de dados que quiser, como poderia não usar banco nenhum caso prefira e continuar usando arquivo estático.

> 2. Adicionar essa banco no docker compose, para que o run já configure tudo (até com valores default)

Localmente podemos usar o SQLite para deixar o ambiente de desenvolvimento leve, e deixamos já configurado no docker. O que acha?

> 3. Adicionar um admin (CRUD) para registrar os emails ou um domínio especifico. Nesse primeiro momento nem precisa ter login de acesso ao admin.

Isso poderia ficar para uma próxima onda de entrega. Mas está fazendo falta mesmo um backoffice/admin para modificar as configurações. Podemos criar outra issue para inciar a conversa sobre isso separadamente.

> 4. Adicionar uma restrição no controler de login para verificar se o email que acabou de se autenticar no Google está dentro dessa whitelist.

Esse whitelist tem que ficar no backend, então para isso precisamos passar a autenticar as URLs privadas. Podemos usar o http://www.passportjs.org/ e o https://github.com/auth0/node-jsonwebtoken para fazer essa autenticação.

> 
> Se seguirmos assim os próximos passos pode ser migrar todas as configs para essa estrutura.
> 
> Veja se faz sentido, se fizer, Eu posso trabalhar nisso.
> 
> \o/ \o/ \o/

Fatia bem as entregas para termos [PR pequenos](https://medium.com/rd-shipit/o-tamanho-do-pull-request-%C3%A9-mais-importante-do-que-voc%C3%AA-pensa-a9cd1df2a0b0) e podermos dividir o trabalho. #tamusjuntos!

**Comment by dherik** [comment]
Hello! 

Do you have some update about the development of this feature? Do you know if someone already started the development?

**Comment by megatroom** [comment]
@dherik now we release version 2.0.0 with new authentication, see [this migration guide](https://github.com/ResultadosDigitais/matrix/blob/master/docs/MIGRATION-TO-V2.md). 

It was included in PR #213

With that we can even close this issue.

**Comment by dherik** [comment]
This is working? It's not working for me. I could login with my personal google account using `WHITELIST_DOMAINS` variable setted.

**Comment by angeliski** [comment]
Hey @dherik
Can you provide a gif for that? And your environment variables?
The feature works nicely here

**Comment by dherik** [comment]
@angeliski it's working. I forgot to `build` the docker-compose again :)
