### ISSUE TITLE
configuration ROOMS_DATA in heroku

### ISSUE THREAD

**Issue by enieber** [ResultadosDigitais/matrix#155]
This project is very nice and I go start test, but I don't how to set default rooms data environment, because in Setup is only in JSON/JS format

**Comment by juliemar** [comment]
Hi @enieber I didn't understand your question. but I'll try to help you :)

in [This](https://github.com/ResultadosDigitais/matrix/blob/master/SETUP.md) documentation we have an exemple:
![image](https://user-images.githubusercontent.com/643779/57637753-8f300d00-7582-11e9-97f1-33aa2dc0eeeb.png)

In heroku go to settings and click in Reveal config Vars:
![image](https://user-images.githubusercontent.com/643779/57637854-cb636d80-7582-11e9-93de-9d29f98ba709.png)

And config like this:
![image](https://user-images.githubusercontent.com/643779/57637966-22694280-7583-11e9-966b-fdc816567dd1.png)

dont forguet to pul `ROOMS_SOURCE` = `ENVIRONMENT`

**Comment by juliemar** [comment]
I'm checking the setup documentation and `ROOMS_SOURCE = ENVIRONMENT` is not documented. @enieber Could you document this and open a PR for us?
