### ISSUE TITLE
Insert Google oauth url callback in README.md

### ISSUE THREAD

**Issue by bcarmo-geru** [ResultadosDigitais/matrix#187]
Insert Google oauth url callback in README.md

## Description
Guys, could you please add what is the Google oauth url callback in README.md? I'm trying to deploy Matrix but I cannot find this information.

Thanks in advance!

**Comment by lccezinha** [comment]
Hello @bcarmo-geru 

Have you tried to check the information in https://github.com/ResultadosDigitais/matrix#environments or https://developers.google.com/identity/sign-in/web/sign-in? 

You need to create your own credentials to be used in the google login.

**Comment by alesshh** [comment]
Fixed
