### ISSUE TITLE
When click "invite user to a meet" and have a externalMeetURL, matrix open "JitsiMeet"

### ISSUE THREAD

**Issue by toedio** [ResultadosDigitais/matrix#222]
## Description
I use matrix in my company and all rooms have external meet url (meet.google.com). When we click in "Invite user to a meet", user confirm and enter in a Jitsi Meet.

Always when a user accepct invitation have a console log that show externalMeetURL variable value. App is logging correctly the external meet url but open a jitsi meet

### Steps to Reproduce
1. Enter a room that have externalMeetURL
2. Invite a user

### Expected Behavior
- Open external meet link

### Current Behavior
- Open Jitsi Meet

**Comment by juliemar** [comment]
Thanks for open this issue. Could you try to fix and open a PR?

**Comment by toedio** [comment]
Of course. I will try to do this at the weekend
