### ISSUE TITLE
GOOGLE_CREDENTIAL variable is still mandatory

### ISSUE THREAD

**Issue by dherik** [ResultadosDigitais/matrix#254]
Hi!

I'm using the last version on master and the `GOOGLE_CREDENTIAL` is still mandatory. Without this variable, the Google sign-in button not appears for me.

My current environment variables:

```
GOOGLE_CLIENT_ID=5599454545454-jahsdasdhasudhauhsdasdasdsd.apps.googleusercontent.com
GOOGLE_CREDENTIAL=5599454545454-jahsdasdhasudhauhsdasdasdsd.apps.googleusercontent.com
GOOGLE_SECRET=DSmjg-jahsdkjahdkjashdkjahsd
GOOGLE_CALLBACK_URL=https://matrix.domain.com
ENFORCE_SSL=false
ROOMS_DATA=[{"id":"dsdasd-f5555-ddsss-ddaaa-3434343434","name":"Sala de Reunião"}]
WHITELIST_DOMAINS=["@domain.com"]
COOKIE_SESSION_SECRET=matrix
COOKIE_SESSION_MAX_AGE=2592000000
ROOMS_SOURCE=ENVIRONMENT
```

**Comment by juliemar** [comment]
Hi @dherik,

Probably your Docker image is outdated. Try to update the repository and rebuild your Docker image   
1. `git checkout master` 
2. `git pull origin master`
3. `docker-compose up --build`

**Comment by dherik** [comment]
Man, I forgot the `build`. Shame on me, I will close the two last issues and try again tomorrow
