### ISSUE TITLE
Whitelist domains not working

### ISSUE THREAD

**Issue by dherik** [ResultadosDigitais/matrix#255]
Hi!

I saw the new features in the last version, but the `WHITELIST_DOMAINS` variable it's not working for me.

Even setting the variable with the allowable domains, I can sign-in on the Matrix using my Google personal account.

My current variables are:

```
GOOGLE_CLIENT_ID=5599454545454-jahsdasdhasudhauhsdasdasdsd.apps.googleusercontent.com
GOOGLE_CREDENTIAL=5599454545454-jahsdasdhasudhauhsdasdasdsd.apps.googleusercontent.com
GOOGLE_SECRET=DSmjg-jahsdkjahdkjashdkjahsd
GOOGLE_CALLBACK_URL=https://matrix.domain.com
ENFORCE_SSL=false
ROOMS_DATA=[{"id":"dsdasd-f5555-ddsss-ddaaa-3434343434","name":"Sala de Reunião"}]
WHITELIST_DOMAINS=["@mydomain.com"]
COOKIE_SESSION_SECRET=matrix
COOKIE_SESSION_MAX_AGE=2592000000
ROOMS_SOURCE=ENVIRONMENT
```

**Comment by juliemar** [comment]
Hi @dherik could you confirm if you are running the latest #matrix version? It is not necessary for the  `GOOGLE_CREDENTIAL` variable. You can remove It.

Try to update `git pull` and `docker-compose up --build`

**Comment by dherik** [comment]
Man, I forgot the `build`. Shame on me, I will close the two last issues and try again tomorrow
