### ISSUE TITLE
Add a description for the room

### ISSUE THREAD

**Issue by dherik** [ResultadosDigitais/matrix#306]
## Description
Hi!

I would like to suggest an optional new field for each room: `description`.

If you have many rooms, sometimes the people are confused about where is the "correct" room to start a meeting. If you have some description to guide them will be great.

The description could be showed on two ways:

1. When you hover the mouse on the room on the rooms page
2. When you enter the meeting, on the side of the header title

For example:

![War_Room_Screenshot_2020-04-09_09-52-48](https://user-images.githubusercontent.com/839745/78897314-5c1f2380-7a48-11ea-8d22-6bf5e635c891.png)
![War_Room_Screenshot_2020-04-09_09-54-32](https://user-images.githubusercontent.com/839745/78897322-5f1a1400-7a48-11ea-9c7d-c6af823e2388.png)

**Comment by juliemar** [comment]
Hi @dherik this field is so usual. could you open a PR with this suggestion?
