### ISSUE TITLE
User icon appears in all rooms at same time

### ISSUE THREAD

**Issue by danilorsilva** [ResultadosDigitais/matrix#307]
## Description
I have installed matrix on kubernetes.

When i access the Matrix url i can authenticate successfully and access my matrix web interface.

My problem is that my user appears on all rooms.

### Expected Behavior
My user icon appears only in the room that i enter.

### Current Behavior
My user icon appears in all rooms not in only one.

Thanks!

**Comment by danilorsilva** [comment]
The ${UUID} is not working, so, all the rooms have the same name.

I set manually all UUIDs and it works.

**Comment by angeliski** [comment]
Hey @danilorsilva Thanks for your report! The ${UUID} is just an example, but maybe the documentation is not clear about that. We will try to fix that.
