### ISSUE TITLE
refatorar o codigo para js moderno

### ISSUE THREAD

**Issue by rfukui** [ResultadosDigitais/matrix#31]
para garantir mais pessoas contribuindo é bom que ele seja escrito da forma mais moderna

**Comment by dvinciguerra** [comment]
+1

**Comment by luan0ap** [comment]
Seria interessante **pensar** na possibilidade de remover o JQuery do projeto também. O JS já nos permite fazer muita coisa sem a necessidade dele, o que acontece em seletores (o famoso seletor `$` pode ser escrito facilmente com `arrow function` ou `bind function`), chamadas ajax (com o `Fetch API`), etc. 

[Existe um artigo no próprio github](https://github.com/nefe/You-Dont-Need-jQuery/blob/master/README.pt-BR.md) que explica como podemos escrever facilmente funções do JQuery usando vanilla.

Caso o problema for o uso do bootstrap,[ no próprio blog dele](https://blog.getbootstrap.com/2019/02/11/bootstrap-4-3-0/), é comentado sobre a remoção do JQuery como dependência.

**Comment by alesshh** [comment]
Comecei um PR que configura o webpack e instala as dependencias via npm.
https://github.com/ResultadosDigitais/matrix/pull/139
O próximo passo que vejo é remover jQuery, e talvez, evoluirmos p/ react, dado que temos algumas features que queremos como criação de salas, etc.

**Comment by jorgemdnt** [comment]
@alesshh Acho que essa issue está um pouco abstrata, o que acham de quebrarmos essa issue em menores mais práticas? Ex.: 
1. Limpar erros do linter;
2. Remover o jquery;
3. Usar es6 em todos os arquivos JS;
4. Evoluir front-end para React (?)

**Comment by alesshh** [comment]
@jorgemdnt total sentido

**Comment by megatroom** [comment]
Gostaria de contribuir para essa migração para o React, mas acho válido discutir alguns pontos antes para evitar retrabalho:

1. Ao escrever o código novo, já iria atendendo as regras do linter. Porém, as regras do linter está a mesma para o backend e frontend, acho válido separar as regras para melhor resultado.
2. Acho ótimo o [monorepo](https://en.wikipedia.org/wiki/Monorepo), mas não seria melhor ter um package.json para o backend e outro para o frontend? Fica difícil identificar quais são as dependências de cada projeto, fora que facilitaria o uso diferentes de libs para cada projeto. Por exemplo, poderia manter o [Mocha](https://mochajs.org/) para testes do backend e passar a usar o [Jest](https://jestjs.io/) para os testes do frontend React.
3. Manter a configuração personalizada do webpack (sem usar o [CRA](https://facebook.github.io/create-react-app/)).
4. Usar o [React Hooks](https://reactjs.org/docs/hooks-intro.html) e usar classes só em casos muito especiais (como no caso de usar o _componentDidCatch_).
5. Usar [contexto](https://reactjs.org/docs/context.html) para estado global e não usar Redux/MobX.
6. Usar [lazy loading](https://reactjs.org/docs/code-splitting.html) dos componentes.
7. Separar [componentes de apresentação e de comportamento](https://medium.com/@dan_abramov/smart-and-dumb-components-7ca2f9a7c7d0).
8. Usar validador de tipagem como PropTypes, Flow ou TypeScript?

Já que estamos falando de re-design da arquitetura, tem algumas mudanças que podemos discutir, mas que poderia ficar para uma segunda fase, para não mudar muita coisa em um PR só:

1. Passar a usar o [SASS](https://sass-lang.com/) em vez de escrever o CSS direto.
2. Passar a usar o [BEM](http://getbem.com/) para o nome das classes CSS/SCSS.
3. Vale manter o Bootstrap? Não vejo problema em manter, mas se for alterar os estilos pode ser um bom momento para levantar essa discussão.

O que acham?

**Comment by alesshh** [comment]
@megatroom eu comecei a reescrever algumas coisas de maneira baby steps. Comecei pela de login e estava iniciando a página do office. Ainda está sem testes nessa camada, mas penso que o caminho seja jest e talvez o https://airbnb.io/enzyme/.

Não usei o CRA, apenas configurei o webpack (hoje é usado só p/ frontend), com CSS modules, quebrando alguns arquivos, e penso que a ideia é seguir de maneira simples, sem Redux e usando PropTypes.

Hoje o roteamento acontece no server, penso que o passo após a reescrita do office é matar isso, e implementar o react router + lazy components.


Sobre o CSS minhas skills estão um pouco enferrujadas, fique à vontade em propor melhorias nisso.

O intuito desde o início do projeto é mantê-lo simples, e simples de rodar. Hoje o backend compartilhar o mesmo package.json é um problema sim, penso que podemos separar isso, mantendo sempre a simplicidade.

Acho que um bom ponto de partida seria criarmos um mini roadmap p/ onde estamos indo.

**Comment by megatroom** [comment]
@alesshh gostei da idea do roadmap, fica até mais fácil distribuir as tarefas.

Sobre o teste, poderia ser o Jest com o [React Testing Library](https://testing-library.com/docs/react-testing-library/intro), ele faz o mesmo que o Enzyme, mas ele é muito mais simples e robusto. 

Também acho uma boa fazer teste de integração, o [Cypress](https://www.cypress.io/) é uma boa opção para isso, eu falo dele em um [artigo que fiz no Medium](https://medium.com/m4u-tech/refatorando-c%C3%B3digo-legado-em-projetos-react-parte-i-2214fd9ee04d).

Acho uma boa usar o React Router, fica até mais fácil caso alguém queira hospedar o frontend em lugar diferente do backend.

Ajudo com o CSS sim, tanto na estrutura e codificação, quanto na responsividade.

Sobre o package.json, dá para manter a simplicidade em ter um package.json central na raiz do projeto e ainda sim cada projeto ter o seu. Pode ser usado o [Lerna](https://github.com/lerna/lerna) para fazer isso, ou pode ser usado também o [Yarn workspaces](https://yarnpkg.com/lang/en/docs/workspaces/).  

Como você já começou, vê qual seria os próximos passos a partir do que você já fez, que assim eu e outros podemos pegar um desses passos para contribuir. Talvez até criar uma issue para cada um desses passos para discutir separadamente.

**Comment by alesshh** [comment]
Poxa, não sabia que o yarn tinha essa feature <3, parece ser um bom candidato, já que é algo mais comum de se ver por aí.
Vou tentar quebrar umas tarefas e organizarmos p/ termos ideia do que precisa ser feito. 🚀

**Comment by juliemar** [comment]
I'm closing this issue because now we have react.js
