### ISSUE TITLE
Play sound while invite dialog is shown

### ISSUE THREAD

**Issue by joseantonnio** [ResultadosDigitais/matrix#312]
When I'm with #matrix tab running in background, my coworkers always need to send me a Slack message with "hey! we're inviting you to a meeting inside the #matrix". 

Almost every invite notification that I receive goes unnoticed. So it would be very good have an incoming call sound playing while invite dialog is shown (Skype or Slack like).

## Description

Play a ringtone sound (something like [this one](https://actions.google.com/sounds/v1/household/phone_ringing.ogg)) while invite dialog is shown to user. When the user cancel or accept the invite the sound stops playing.

### Additional context

Offtopic: Here at my work we're using #matrix and it's working quite good. Probably I'll be here time to time with some new ideas or bugs. Hope I can help with some PRs too but React and Node aren't my cup of tea :laughing:

**Comment by juliemar** [comment]
Hi @joseantonnio this is a good idea. I'm looking some kind of sound that represents the #matrix movie. Do you have some suggestions?

**Comment by joseantonnio** [comment]
On the first movie, Neil receives a Nokia get instructions from Morpheus when he is at work. It's not the Nokia default ringtone that plays but a generic one. Think would be a very nice choice.

Here's the scene: https://www.youtube.com/watch?v=Lweuy1X9Tcg

**Comment by joseantonnio** [comment]
On the first movie, Neo receives a Nokia to get instructions from Morpheus when he is at work. It's not the Nokia default ringtone that plays but a generic one. Think would be a very nice choice.

Here's the scene: https://www.youtube.com/watch?v=Lweuy1X9Tcg

**Comment by joseantonnio** [comment]
After googled "nokia matrix ringtone" I found this: https://www.zedge.net/ringtone/de0436b6-69d9-32fe-b5af-8ffefd6b7645 :smiley:

**Comment by phiter** [comment]
@joseantonnio did you try my solution? It has been merged to develop branch.

If it works I think this issue can be closed :D

**Comment by joseantonnio** [comment]
@phiter works like a charm :+1: 

Thank you! And I'm sorry for the late answer...
