### ISSUE TITLE
share room link to anothers users

### ISSUE THREAD

**Issue by juliemar** [ResultadosDigitais/matrix#32]
## Description
sometimes we need to share the room link to other users. 

### Expected Behavior
- when I copy current room url and send to other user this second user should enter in the same room that I'm.

### Current Behavior
- today is not possible todo this.

### Possible Solution
Sugestion: add an anchor of roomId in URL:
EX: 
localhost:8080/office#room-1
localhost:8080/office#room-3

**Comment by felipecdo** [comment]
@juliemar this issue can be closed, right?

**Comment by juliemar** [comment]
Nop there is a bug... when the user is not logged. the login page not redirect to previous office url.
