### ISSUE TITLE
Matrix is always asking the user to enter call when he enters a new room

### ISSUE THREAD

**Issue by lgiacomini92** [ResultadosDigitais/matrix#35]
## Description
Matrix is always asking the user to enter call when he enters a new room, even though when the room does not have a call or when the room was empty.

### Steps to Reproduce
1. Open Matrix
1. Enter in a empty room

### Expected Behavior
- I should be asked if I want to create a new call

### Current Behavior
- I'm asked if I want to enter in the call
![image](https://user-images.githubusercontent.com/6638683/55490280-e8169800-5609-11e9-8c21-2cf1c75ac313.png)

**Comment by raphaelln** [comment]
@lgiacomini92 Could we close this issue ? I believe the `Lounge` room has this capability.

This implementation could be found at #83

**Comment by jeantoledo** [comment]
Already fixed!
