### ISSUE TITLE
Rename ExpansionPanel

### ISSUE THREAD

**Issue by silvanavlima** [ResultadosDigitais/matrix#352]
### Cleanup

**What should be cleaned up or changed**:
The ExpansionPanel component was renamed to Accordion and
the change generated errors at the console.

**Provide any links for context**:
[https://ibb.co/zXkxpPQ](https://ibb.co/zXkxpPQ)

that's my suggestion [PR](https://github.com/ResultadosDigitais/matrix/pull/351)

**Comment by juliemar** [comment]
Hi @silvanavlima good suggestion. Feel free to open a PR to us with :)

**Comment by juliemar** [comment]
fixed by https://github.com/ResultadosDigitais/matrix/pull/351
