### ISSUE TITLE
Magic number

### ISSUE THREAD

**Issue by silvanavlima** [ResultadosDigitais/matrix#354]
### Cleanup

**What should be cleaned up or changed**:
To avoid problems with "number magic" in the future
My suggestion is to change comments by a variable. It is easier to read and understand.

**Provide any links for context**:
[Code](https://ibb.co/XLSrKzR)

That's my [suggestion ](https://github.com/ResultadosDigitais/matrix/pull/353)

**Comment by juliemar** [comment]
fixed by: https://github.com/ResultadosDigitais/matrix/pull/353
