### ISSUE TITLE
Less colors saturated 

### ISSUE THREAD

**Issue by silvanavlima** [ResultadosDigitais/matrix#356]
### Subject of the issue
The colors primary and secondary of the dark/light theme are equals. In mode dark, these colors more become saturated colors and vibrant. Check [here.](https://ibb.co/9YF96JZ)

### Possible Solution
Change colors primary and secondary for less colors saturated.

My suggestion [ PR](https://github.com/ResultadosDigitais/matrix/pull/355)

**Comment by juliemar** [comment]
fix: https://github.com/ResultadosDigitais/matrix/pull/355
