### ISSUE TITLE
The logo of the matrix was without the alt attribute. 

### ISSUE THREAD

**Issue by silvanavlima** [ResultadosDigitais/matrix#358]
### Subject of the issue

The logo of the matrix was without the attribute alt. 

### Steps to reproduce

Inspect logo.

### Possible Solution

It is an important attribute used specifies an alternate text for an image that cannot be displayed.
The project has the option switch language, so I took advantage of the opportunity to add the option at alt in English/Portuguese.
[My suggestion here.](https://github.com/ResultadosDigitais/matrix/pull/357)

**Comment by juliemar** [comment]
fixed by https://github.com/ResultadosDigitais/matrix/pull/357
