### ISSUE TITLE
Language switch problem (Problema na troca de idioma)

### ISSUE THREAD

**Issue by ezlage** [ResultadosDigitais/matrix#371]
### Subject of the issue

I created a laboratory to test the Matrix, but when I use the language switch to PT-BR, it has no effect. I tried to log out and login, but the problem persisted. The Google authentication screen is ok. I did not find related information in the documentation. Can I do anything to force the language to PT-BR?  
  
Criei um laboratório para testar o Matrix, mas quando utilizo a troca de idioma para PT-BR, não surte efeito. Tentei fazer logout e login, mas o problema persistiu. A tela de autenticação do Google está ok. Não encontrei informações relacionadas na documentação. Posso fazer algo para forçar o idioma para PT-BR?  

### Steps to reproduce

Log in, switch the language.  
  
Faça login, mude o idioma.   

### Expected behaviour

The language should change according to the selection.  
  
O idioma deveria alterar conforme a seleção.  

### Actual behaviour

Nothing happens (even after log out and log in).  
  
Nada acontece (mesmo depois de fazer logout e login).  

### Possible Solution

I did not identify.  
  
Eu não identifiquei.

**Comment by phiter** [comment]
Not every string has been translated yet. I had everything translated on #342 but it needs to be split into multiple PRs. If someone wants to do that, it would be great.

**Comment by ezlage** [comment]
Hello, phiter!

I will take a look. If I realized that I'm able to, I will try to split into multiple PRs.

Thank you!

**Comment by ezlage** [comment]
Following Phiter suggestion, I could solve the problem just bringing another branch to production.

```bash
`git clone https://github.com/ResultadosDigitais/matrix -b '#341-add-i18n' matrix`
