### ISSUE TITLE
Be able to get an user into the current room

### ISSUE THREAD

**Issue by diegocsandrim** [ResultadosDigitais/matrix#46]
## Description
As a matrix user I want to get a user into the room I am, so I can easily communicate with him.

## User case
I click with the rigth button in the person and choose the option "Get Paul".
Paul receives a notification saying that I want to talk to him.
Paul clicks in Ok button, and is redirected to the room

**Comment by juliemar** [comment]
we can use [this](https://jsfiddle.net/KyleMit/X9tgY/) sample to implement the right click on user photo.

**Comment by juliemar** [comment]
Branch: https://github.com/juliemar/matrix/tree/get-user

**Comment by juliemar** [comment]
we delivered an experiment with the right click button to ask another person to join a meeting
