### ISSUE TITLE
Logout is not working after user sign in

### ISSUE THREAD

**Issue by lgiacomini92** [ResultadosDigitais/matrix#61]
## Description
Logout is not working when the user clicks on Logout button. 
**OBS:** If the user reloads the page and clicks the Logout button a few times, the logout works

### Steps to Reproduce
1. Access Matrix login page
1. Sign in Matrix using a google account
1. Once you have redirected to the office page, click the Logout button in the navbar

### Expected Behavior
- Your account must be disconnected and you must be redirected to the login page.

### Current Behavior
- An error occurs and logout is not working
![image](https://user-images.githubusercontent.com/6638683/55741754-66a57800-5a04-11e9-8083-7aefde82dec0.png)

**Comment by lccezinha** [comment]
I'm gonna try to solve it!
