### ISSUE TITLE
Salas no jitsi estão publicas

### ISSUE THREAD

**Issue by rtancman** [ResultadosDigitais/matrix#77]
O jitsi por padrão cria as salas publicas e por este motivo qualquer usuario pode ir na home e descobri o nome da sala que estamos utilizando no matrix. Ex:
![matrix-jitsi](https://user-images.githubusercontent.com/596684/55977732-e8481080-5c65-11e9-9ded-084847cde5fe.gif)

**Comment by juliemar** [comment]
As salas são criadas via variável de ambiente. Fiz uma alteração para o id da sala ser um UUID. O que vc acha desta solução parcial?

**Comment by lccezinha** [comment]
@juliemar @rtancman essa issue ainda é válida, ou foi fechada no #78 ?

**Comment by juliemar** [comment]
opa podemos fechar ela, agora um externo precisa ter o uuid da sala para conseguir fazer o reportado neste chamado

**Comment by juliemar** [comment]
This PR https://github.com/ResultadosDigitais/matrix/pull/148 concatenate host in the room id to prevent this situation. but for really solve we have to enable the client to define the hosted jitisi url.
